apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-webapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-test-webapi
  template:
    metadata:
      labels:
        app: k8s-test-webapi
    spec:
      containers:
      - name: webapi
        # 替换为你的DockerHub账号
        image: shuangliao/k8s-test-webapi:v1.0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-test-webapi-svc
spec:
  selector:
    app: k8s-test-webapi
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP